package StartPage;


import StartPage.JFrameHomePage;
import AdminPage.HomePage;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;



        

/**
 *
 * @author Sadeer
 */
public class AdminSignIn extends javax.swing.JFrame {

    
    
    /**
     * Creates new form signinTeacher
     */
    public AdminSignIn() {
        initComponents();
        setVisible(true);
        connectToDb();
        getContentPane().setBackground(Color.white);
         
    }
// anslutning till databasen
    private void connectToDb()
    {
         File db = new File("Namn på databas filen");
            System.out.println(db.getAbsolutePath());
            try {
                databas = new InfDB(db.getAbsolutePath());
            } 
            catch (InfException ex) {
                System.out.println(ex.getMessage());
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pwfldPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JTextField();
        LblInTeacherSignIn = new javax.swing.JLabel();
        BtnSignIn = new javax.swing.JButton();
        BtnReturn = new javax.swing.JButton();
        LblInSignInFail = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        lblUserName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("Username");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(101, 111, 98, 25);

        lblPassword.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(101, 165, 80, 17);

        pwfldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfldPasswordActionPerformed(evt);
            }
        });
        pwfldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwfldPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(pwfldPassword);
        pwfldPassword.setBounds(247, 160, 110, 26);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(247, 110, 110, 26);

        LblInTeacherSignIn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblInTeacherSignIn.setForeground(new java.awt.Color(255, 255, 255));
        LblInTeacherSignIn.setText("Sign in to your account");
        getContentPane().add(LblInTeacherSignIn);
        LblInTeacherSignIn.setBounds(80, 10, 280, 33);

        BtnSignIn.setText("Sign In");
        BtnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSignIn);
        BtnSignIn.setBounds(159, 219, 87, 29);

        BtnReturn.setForeground(new java.awt.Color(255, 0, 0));
        BtnReturn.setText("Return");
        BtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(BtnReturn);
        BtnReturn.setBounds(301, 300, 85, 29);

        LblInSignInFail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        LblInSignInFail.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(LblInSignInFail);
        LblInSignInFail.setBounds(21, 254, 254, 38);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(6, 298, 75, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StartPage/Blue03.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 350);

        setSize(new java.awt.Dimension(418, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void pwfldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfldPasswordActionPerformed
// metod som kotrolerar om namnet och lösenordent stämmer
    private void BtnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignInActionPerformed
        Validation validation = new Validation(); 
        String admin = "";
        txtPassword.requestFocusInWindow();
 LblInSignInFail.setText(null);
String password = pwfldPassword.getText();
String userName = txtPassword.getText();
// skriver ut ett fel meddelande om  användnamnet eller lösenordent är fälten ät tomma
if(!validation.four(userName)|| !validation.five(password)){
    LblInSignInFail.setText("Wrong username or password"); 
pwfldPassword.setText(null);
    txtPassword.setText(null);
}
else{
try
{
    // kotrolerar om alla info stämmer
    String sql = "select larar_id, losenord, administrator from LARARE where efternamn = '"+userName+"' and losenord = '"+password+"'";
    //Iteration genom ArrayListan larare.
                ArrayList<HashMap<String, String>> teacher = databas.fetchRows(sql);
                if (teacher == null){
                    JOptionPane.showMessageDialog(null, "login failed!.");
                }
            for (int i = 0; i < teacher.size(); i++) { 
             
                String id = teacher.get(i).get("LARAR_ID");
                String pass = teacher.get(i).get("LOSENORD"); 
                admin = teacher.get(i).get("ADMINISTRATOR"); 
                String lastname = teacher.get(i).get("EFTERNAMN");
            }
            //  meddelande vid rätt inmatning av användnamnet eller lösenordent
    if (teacher != null){
        if(admin.equals("T")){
            new HomePage();
            dispose();
        }
        else{
            new JFrameHomePage();
            dispose();
dispose();
        }
            
    }
    
    else{
        pwfldPassword.setText(null);
    txtPassword.setText(null);
LblInSignInFail.setText("login failed");
    }
}
catch(InfException ex)
{
    System.out.println(ex.getMessage());
}   


}
    }//GEN-LAST:event_BtnSignInActionPerformed

    private void pwfldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfldPasswordKeyPressed


    }//GEN-LAST:event_pwfldPasswordKeyPressed

    private void BtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnActionPerformed
        new Homepage();
        dispose();
    }//GEN-LAST:event_BtnReturnActionPerformed
// info knapp för hjälp vid inlogning
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JOptionPane.showMessageDialog(null, "Username Is Your Lastname. Capitalization must match.");
    }//GEN-LAST:event_jButton1ActionPerformed

private InfDB databas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReturn;
    private javax.swing.JButton BtnSignIn;
    private javax.swing.JLabel LblInSignInFail;
    private javax.swing.JLabel LblInTeacherSignIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField pwfldPassword;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
