/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StartPage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ellin
 */
public class ChooseMeetingTime extends javax.swing.JInternalFrame {
    
    private static Connection con;
    private MethodService methodService;

    /**
     * Creates new form EditBlogInternalFrame
     */
    public ChooseMeetingTime(Connection con) {
        initComponents();
        this.con = con;
        fillComboBox();
        fyllAreaInvited();
        fyllValtTid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxOption = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnChoose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaChoose = new javax.swing.JTextArea();
        lbChoose = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAccepterat = new javax.swing.JTextArea();
        lblParcipant = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaInvited = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Örebro universitet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        cbxOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one option" }));

        jLabel2.setText("Date:");

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        txtAreaChoose.setColumns(20);
        txtAreaChoose.setRows(5);
        jScrollPane1.setViewportView(txtAreaChoose);

        lbChoose.setText("Choosen dates:");

        txtAreaAccepterat.setColumns(20);
        txtAreaAccepterat.setRows(5);
        jScrollPane2.setViewportView(txtAreaAccepterat);

        lblParcipant.setText("Participant:");

        txtAreaInvited.setColumns(20);
        txtAreaInvited.setRows(5);
        jScrollPane3.setViewportView(txtAreaInvited);

        jLabel3.setText("Intvited to meeting:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(cbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnChoose)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbChoose)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblParcipant))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbChoose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(btnChoose))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParcipant)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void fyllAreaInvited()
    {
        Statement stmt = null;
        String lista = "";
        
        try
        {
            stmt = con.createStatement();
            int userID = LoggedUser.getID();
            
            String fraga = "Select MID from PERSONER_DELTAR where ID = ?";
            PreparedStatement ps = con.prepareStatement(fraga);
            ps.setInt(1, userID);
            ResultSet rs = ps.executeQuery();
            rs.next();
            int motesID = rs.getInt("MID");
            
            
            String fraga1 = "select FNAMN, ENAMN from PERSONER "
                    + "join PERSONER_DELTAR on PERSONER.ID = PERSONER_DELTAR.ID "
                    + "where PERSONER_DELTAR.MID = ?";
            
            PreparedStatement ps2 = con.prepareStatement(fraga1);
            ps2.setInt(1, motesID);
            ResultSet rs1 = ps2.executeQuery();
                
            while(rs1.next())
            {
                lista += rs1.getString("FNAMN");
                lista += " ";
                lista += rs1.getString("ENAMN");
                lista += "\n";    
            }
            txtAreaInvited.setText(lista);     
        }
        catch(SQLException ex1)
        {
            JOptionPane.showMessageDialog(null, "Something went wrong.");
        }
    }
    
    private void fyllValtTid()
    {
         try{
                Statement stmt = con.createStatement();
                int userID = LoggedUser.getID();
                String lista = "";
                
                String fraga = "Select MID from PERSONER_DELTAR where ID = ?;";
                PreparedStatement ps = con.prepareStatement(fraga);                
                ps.setInt(1, userID);
                ResultSet rs = ps.executeQuery();
                rs.next();
                int motesID = rs.getInt("MID");
                
                String fraga2 = "select FNAMN,ENAMN,START_TID,SLUT_TID from PERSONER"
                                + " join PERSON_ACCEPTERAT on PERSONER.ID = PERSON_ACCEPTERAT.ID"
                                + " join MOTES_FORSLAG on PERSON_ACCEPTERAT.FORSLAGS_ID = MOTES_FORSLAG.FORSLAGS_ID"
                                + " where MOTES_FORSLAG.MID = ?";

                PreparedStatement ps1 = con.prepareStatement(fraga2);
                ps1.setInt(1, motesID);
                ResultSet rs1 = ps1.executeQuery();
                
                
                while (rs1.next())
                {
                    lista += rs1.getString("FNAMN");
                    lista += " ";
                    lista += rs1.getString("ENAMN");
                    lista += " ";    
                    lista += rs1.getString("START_TID");
                    lista += " ";  
                    lista += rs1.getString("SLUT_TID");
                    lista += "\n";    
                }
                txtAreaAccepterat.setText(lista);
                
            } catch(SQLException ex2)
            {
                JOptionPane.showMessageDialog(null, "Something went wrong1.");
            }
        
    }
    
    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        if(Validation.elementSelectedInCombobox(cbxOption, "Choose an element from the combobox."))
        {
           try
            {
                Statement stmt = con.createStatement();
                String tid = cbxOption.getSelectedItem().toString();
                int userID = LoggedUser.getID();

                String fraga = "Select MID from PERSONER_DELTAR where ID = ?;";
                PreparedStatement ps = con.prepareStatement(fraga);                
                ps.setInt(1, userID);
                ResultSet rs = ps.executeQuery();
                rs.next();
                int motesID = rs.getInt("MID");
                
                txtAreaChoose.setText(tid); //Lägger in den valda tiden i textArean.
                
                String[] user = cbxOption.getSelectedItem().toString().trim().split(" till "); //delar upp varje item i comboboxen i start och sluttid.
                String start = user[0];
                String end = user[1];
            
                //Hämtar FORSLAGS_ID, kollar så att slut och starttiden för ett möte är olika,
                //i och med att det inte ska finnas två exakt samma förslagtider för ett möte
                String fraga2 = "select FORSLAGS_ID from MOTES_FORSLAG where START_TID = ? and SLUT_TID = ? and MID = ?;";
                PreparedStatement ps1 = con.prepareStatement(fraga2);                
                ps1.setString(1, start);
                ps1.setString(2, end);
                ps1.setInt(3, motesID);
                ResultSet rs1 = ps1.executeQuery();
                rs1.next();
                int forslagsID = rs1.getInt("FORSLAGS_ID");
                
               
                
                String rosterFraga = "select MAX(ROSTER) as ROSTER from MOTES_FORSLAG where FORSLAGS_ID = ?;";
                PreparedStatement ps2 = con.prepareStatement(rosterFraga);
                ps2.setInt(1, forslagsID);
                ResultSet rs2 = ps2.executeQuery();
                rs2.next();
                int maxRosterInt = rs2.getInt("ROSTER");
                int maxInt = maxRosterInt + 1;
                
                String fraga3 = "update MOTES_FORSLAG set ROSTER = ? where FORSLAGS_ID = ?;";
                PreparedStatement ps3 = con.prepareStatement(fraga3);
                ps3.setInt(1, maxInt);
                ps3.setInt(2, forslagsID);
                ps3.executeUpdate();
                
                String fraga4 = "insert into PERSON_ACCEPTERAT values(?, ?);";
                PreparedStatement ps4 = con.prepareStatement(fraga4);
                ps4.setInt(1, forslagsID);
                ps4.setInt(2, userID);
                ps4.executeUpdate();
                
            }
            catch(SQLException ex3)
            {
                JOptionPane.showMessageDialog(null, "Something went wrong.2");
            }
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    private void fillComboBox(){
        Statement stmt = null;
      
            try
            {
                int id = LoggedUser.getID();
                
                stmt = con.createStatement();
                String fraga = "Select MID from PERSONER_DELTAR where ID = ? ";
                PreparedStatement ps = con.prepareStatement(fraga);                
                ps.setInt(1, id);
                ResultSet rs = ps.executeQuery();
                rs.next();
                int motesID = rs.getInt("MID");
                
                String fraga1 = "Select START_TID, SLUT_TID from MOTES_FORSLAG where MID = ?;";
                PreparedStatement ps1 = con.prepareStatement(fraga1);                
                ps1.setInt(1, motesID);
                ResultSet rs1 = ps1.executeQuery();
                while(rs1.next())
                {
                    String start = rs1.getString("START_TID");
                    String slut = rs1.getString("SLUT_TID");
                    cbxOption.addItem(start + " till " + slut);
                }
            }
            catch(SQLException ex4)
            {
                JOptionPane.showMessageDialog(null, "Something went wrong3.");
            }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private javax.swing.JComboBox<String> cbxOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbChoose;
    private javax.swing.JLabel lblParcipant;
    private javax.swing.JTextArea txtAreaAccepterat;
    private javax.swing.JTextArea txtAreaChoose;
    private javax.swing.JTextArea txtAreaInvited;
    // End of variables declaration//GEN-END:variables
}
