/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StartPage;

import com.jidesoft.swing.AutoCompletion;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ellin
 */
public class EditBlogInternalFrame extends javax.swing.JInternalFrame {
    
    private static InfDB idb;
    private MethodService methodService;
    private String blogID;

    /**
     * Creates new form EditBlogInternalFrame
     */
    public EditBlogInternalFrame(InfDB idb) {
        initComponents();
        this.idb = idb;
        methodService = new MethodService(idb);
        blogID = null;
        //Gör listan sökbar.
        AutoCompletion editablePostList = new AutoCompletion(cbPosts);
        //fillListWithPosts();
        mainPanel.setVisible(false);
        lblChanges.setVisible(false);
        lblChanges2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPosts = new javax.swing.JComboBox<>();
        mainPanel = new javax.swing.JTabbedPane();
        textPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        tfHeading = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taText = new javax.swing.JTextArea();
        lblChanges = new javax.swing.JLabel();
        categoryPanel1 = new javax.swing.JPanel();
        lblDescription1 = new javax.swing.JLabel();
        lblBranch = new javax.swing.JLabel();
        cbMainCategory1 = new javax.swing.JComboBox<>();
        lblMainCategory1 = new javax.swing.JLabel();
        cbSubcategory1 = new javax.swing.JComboBox<>();
        lblTopic = new javax.swing.JLabel();
        cbSubSubcategory1 = new javax.swing.JComboBox<>();
        btnSave3 = new javax.swing.JButton();
        lblChanges2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblChoosepostToEdit = new javax.swing.JLabel();
        btnChooseThisPost = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Örebro universitet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(733, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        cbPosts.setEditable(true);
        cbPosts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a post" }));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblHeading.setText("Heading");

        tfHeading.setColumns(30);

        taText.setColumns(20);
        taText.setRows(5);
        jScrollPane1.setViewportView(taText);

        lblChanges.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChanges.setText("Your changes have been saved!");

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(textPanelLayout.createSequentialGroup()
                        .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(textPanelLayout.createSequentialGroup()
                                .addComponent(lblChanges)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave)))
                        .addGap(49, 49, 49))
                    .addGroup(textPanelLayout.createSequentialGroup()
                        .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading)
                            .addComponent(tfHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(536, Short.MAX_VALUE))))
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(lblChanges))
                .addGap(31, 31, 31))
        );

        mainPanel.addTab("Edit text", textPanel);

        lblDescription1.setText("Choose categories to place your post in another place");

        lblBranch.setText("Branch");

        cbMainCategory1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a category" }));

        lblMainCategory1.setText("Category");

        cbSubcategory1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a topic" }));

        lblTopic.setText("Topic");

        cbSubSubcategory1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a branch" }));

        btnSave3.setText("Save");

        lblChanges2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblChanges2.setText("Your changes have been saved!");

        btnNext.setText("Next");

        btnBack.setText("Back");

        javax.swing.GroupLayout categoryPanel1Layout = new javax.swing.GroupLayout(categoryPanel1);
        categoryPanel1.setLayout(categoryPanel1Layout);
        categoryPanel1Layout.setHorizontalGroup(
            categoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(categoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categoryPanel1Layout.createSequentialGroup()
                        .addComponent(lblChanges2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave3)
                        .addGap(47, 47, 47))
                    .addGroup(categoryPanel1Layout.createSequentialGroup()
                        .addGroup(categoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBranch)
                            .addComponent(lblTopic)
                            .addComponent(lblMainCategory1)
                            .addComponent(lblDescription1)
                            .addGroup(categoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbSubSubcategory1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSubcategory1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMainCategory1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(521, Short.MAX_VALUE))))
        );
        categoryPanel1Layout.setVerticalGroup(
            categoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblDescription1)
                .addGap(71, 71, 71)
                .addComponent(lblMainCategory1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMainCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblTopic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSubcategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblBranch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSubSubcategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(categoryPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave3)
                    .addComponent(lblChanges2)
                    .addComponent(btnNext)
                    .addComponent(btnBack))
                .addGap(24, 24, 24))
        );

        mainPanel.addTab("Edit category", categoryPanel1);

        lblChoosepostToEdit.setText("Choose a post to edit");

        btnChooseThisPost.setText("Choose this post");
        btnChooseThisPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseThisPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChoosepostToEdit)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbPosts, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnChooseThisPost)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblChoosepostToEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseThisPost))
                .addGap(26, 26, 26)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ATT GÖRA:
    //1. Fyll comboboxen med inlägg
    //2. btnCHoose this post Fyll alla fält, comboboxar och areor med värden
    //3. Save
    //4. Save
    //5. Back
    //6. Next


private void fillListWithPosts(){
   // String personID = Inloggning.getID();    
   // try {
            //Hämtar inläggen som användaren har skrivit
     //       ArrayList<HashMap<String, String>> posts = idb.fetchRows("SELECT titel FROM blogg WHERE bloggskribent = \'" + personID + "\'");
       //     cbPosts.setSelectedItem(posts);
        //}
        
        //catch (InfException ettUndantag) {
          //      ettUndantag.getMessage();
            //    JOptionPane.showMessageDialog(null, "Något gick fel.");
            //}
        
        
        
        
    }
    
    
    
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //Uppdaterar inlägget
        if (Validation.textfieldWithValue(tfHeading) && Validation.textareaWithValue(taText)) {
            //Lägger in värdena i de lokala variablerna
            String heading = tfHeading.getText();
            String text = taText.getText();
            
            try {
                //Uppdaterar blogginlägget med den nya titeln och texten
                idb.update("UPDATE blog\n"
                        + "SET titel = \'" + heading + "\', bloggpost = \'" + text + "\n"
                        + "WHERE bloggid = " + blogID);
                lblChanges.setVisible(true);
                
            } 
            catch (InfException ettUndantag) {
                ettUndantag.getMessage();
                JOptionPane.showMessageDialog(null, "Något gick fel.");
            }         
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnChooseThisPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseThisPostActionPerformed
        //Kontrollerar att sökfältet inte är tomt.
        if (Validation.elementSelectedInCombobox(cbPosts, "Choose a post")) {  
            String titel = cbPosts.getSelectedItem().toString();
            try {
             HashMap<String, String> postInfo = idb.fetchRow("SELECT bloggID, bloggpost FROM larare \n" +
                    "WHERE titel = \'" + titel + "\'");
             
             //Fyller i de hämtade värdena i textrutorna för blogginlägget
            tfHeading.setText(titel);
            taText.setText(postInfo.get("BLOGGPOST"));
            blogID = postInfo.get("bloggID");
            
            //Gör panelen synlig
            mainPanel.setVisible(true);
            
            }
            catch (InfException ettUndantag) {
                ettUndantag.getMessage();
                JOptionPane.showMessageDialog(null, "Något gick fel.");
            } 
        }
    }//GEN-LAST:event_btnChooseThisPostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChooseThisPost;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave3;
    private javax.swing.JPanel categoryPanel1;
    private javax.swing.JComboBox<String> cbMainCategory1;
    private javax.swing.JComboBox<String> cbPosts;
    private javax.swing.JComboBox<String> cbSubSubcategory1;
    private javax.swing.JComboBox<String> cbSubcategory1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblChanges;
    private javax.swing.JLabel lblChanges2;
    private javax.swing.JLabel lblChoosepostToEdit;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblMainCategory1;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JTabbedPane mainPanel;
    private javax.swing.JTextArea taText;
    private javax.swing.JPanel textPanel;
    private javax.swing.JTextField tfHeading;
    // End of variables declaration//GEN-END:variables
}
