/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StartPage;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ellin
 */
public class ShowUserInformation extends javax.swing.JInternalFrame {
    
    private static InfDB idb;
    private MethodService methodService;
    private DefaultListModel allUsers;
    //private JList listAllUsers;
    
    /**
     * Creates new form EditBlogInternalFrame
     */
    public ShowUserInformation(InfDB idb) {
        initComponents();
        this.idb = idb;
        methodService = new MethodService(idb);
        fillListWithUsers();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAllUsers = new javax.swing.JList<>();
        btnShowInformation = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taInformation = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Örebro universitet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(729, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        jScrollPane1.setViewportView(listAllUsers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 300, 560));

        btnShowInformation.setText("Show information");
        btnShowInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInformationActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        taInformation.setColumns(20);
        taInformation.setRows(5);
        jScrollPane2.setViewportView(taInformation);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 310, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillListWithUsers() {
        
        try {

            ArrayList<HashMap<String, String>> nameList = idb.fetchRows("SELECT fnamn, enamn FROM personer;");

            //Loopar genom listan för att hämta ut alla för- och efternamn
            for (int i = 0; i < nameList.size(); i++) {
                String firstName = nameList.get(i).get("FNAMN");
                String surName = nameList.get(i).get("ENAMN");
                String user = (firstName + " " + surName + "\n");
                allUsers.addElement(user); 
            }
        } catch (InfException oneException) {
            oneException.getMessage();
            JOptionPane.showMessageDialog(null, "Something went wrong.");
        }
    }
    
    public void snominkod(){
     //if(Validation.valtVarde(listAllUsers.getSelectedValue())){
            try{
                String personInfo = listAllUsers.getSelectedValue();
                String id = personInfo.substring(0,2);
                String fraga = "SELECT BETYG.BETYGSBESKRIVNING, KURS.KURSNAMN from ELEV"
                +" join HAR_BETYG_I on ELEV.ELEV_ID = HAR_BETYG_I.ELEV_ID"
                +" join BETYG on HAR_BETYG_I.KURSBETYG = BETYG.BETYGSBETECKNING"
                +" join KURS on HAR_BETYG_I.KURS_ID = KURS.KURS_ID"
                +" where ELEV.ELEV_ID ="+id;
                ArrayList<HashMap<String,String>> svar = idb.fetchRows(fraga);
                if(svar==null){
                    JOptionPane.showMessageDialog(null, "Den studenten har inga betyg!");
                }
                else{
                    String resultatLista="";
                    for(HashMap rad:svar){ 
                        resultatLista+=rad.get("KURSNAMN");
                        resultatLista+=" ";
                        resultatLista+=rad.get("BETYGSBESKRIVNING");
                        resultatLista+="\n";
                    } 
                    //txtBetygOchKurser.setText(resultatLista);
                }
            }
            catch (InfException e){
                JOptionPane.showMessageDialog(null, "Något gick fel!");
                System.out.println("Internt felmeddelande"+e.getMessage());  
            }
      }
    
    
        private void elevLista(){
        DefaultListModel din=new DefaultListModel();
        try{
            String fraga = "select ELEV_ID,FORNAMN,EFTERNAMN from ELEV";
            ArrayList<HashMap<String,String>> svar = idb.fetchRows(fraga);       
            for(HashMap rad:svar){ 
                String resultatLista="";
                resultatLista+=rad.get("ELEV_ID");
                resultatLista+=" ";
                resultatLista+=rad.get("FORNAMN");
                resultatLista+=" ";
                resultatLista+=rad.get("EFTERNAMN");
                din.addElement(resultatLista);
            } 
            listAllUsers.setModel(din);
            listAllUsers.getSelectedValue();

        }
        catch (InfException e){
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande"+e.getMessage());  
        }
    }   
        
    
    private void btnShowInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInformationActionPerformed
        
       // String kursNamn = allUsers.
            
            
    }//GEN-LAST:event_btnShowInformationActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowInformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listAllUsers;
    private javax.swing.JTextArea taInformation;
    // End of variables declaration//GEN-END:variables
}
